[package]
name = "hbt-core"
version = "0.1.0"
edition = "2024"

[features]
default = ["pinboard"]
pinboard = ["dep:quick-xml", "dep:scraper"]

[dependencies]
pulldown-cmark = { version = "0.13.0", default-features = false, features = ["simd"] }
quick-xml = { version = "0.38.0", optional = true }
scraper = { version = "0.23.1", default-features = false, optional = true }
semver = { version = "1.0.25", features = ["serde"] }
serde.workspace = true
serde_json.workspace = true
thiserror = "2.0.11"
time = { version = "0.3.30", features = ["macros", "parsing", "serde"] }
url = { version = "2.4.1", features = ["serde"] }

[dev-dependencies]
insta = { version = "1.42.0", features = ["json"] }
